### PR TITLE
Addition of PWM support to the DSPAL API, including unit test coverag…

### PR DESCRIPTION
**Pull request by jywilson**
…e in dspal_tester if the correct version of the aDSP firmware is detected.

### CODE REVIEW

**Comment by julianoes** [comment]
Awesome, thanks @jywilson. Is this ready for tests?

**Comment by jywilson** [comment]
It is ready for testing.  You will need the aDSP image which is still going through our internal release process, however.

**Comment by mhkabir** [comment]
What interface will be used for this?

**Comment by twistxj** [comment]
Is there an estimated completion date for this?

**Comment by jywilson** [comment]
This feature will be available in the next release, which is scheduled for the week of August 15th.  The files you will need to update your Snapdragon flight board will be available from Intrinsyc.  When this happens the PR will be merged.

The interface that will be supported for PWM actuation is defined in this header file:
https://github.com/ATLFlight/dspal/blob/PR_pwm_demo_flight_merged/include/dev_fs_lib_pwm.h

**Comment by twistxj** [comment]
Is there an update for this?  Has it been released?

**Comment by jywilson** [comment]
It is available (https://github.com/PX4/Firmware/issues/5394), but as I mentioned we still don't have a DriverFramework driver for it yet.  And you need to be sure to replace the aDSP static image with the one linked at the post referenced above.

We have a PWM DF driver ready, but it's still being tested.  I will post a reply to this issue when the driver is ready.

**Comment by twistxj** [comment]
Sounds good, thanks!

**Comment by jpreiss** [comment]
Hi @jywilson, do you have any estimated release date of the PWM driver?

**Comment by jywilson** [comment]
Not until sometime in January.  Would you have any interest in working on it?  

I can probably get you partially functional driver to work from.

**Pull request merged**
